name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Install libsdl2-dev
      run: sudo apt-get install libsdl2-dev
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: Compress output
      run: mkdir -p squeaker-linux && cp bin/squeaker squeaker-linux && tar -czvf squeaker-linux.tar.gz squeaker-linux
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: squeaker-linux.tar.gz
        path: squeaker-linux.tar.gz
  build_windows:
    runs-on: windows-2019
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: prepare vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && .\vcpkg\bootstrap-vcpkg.bat && vcpkg install sdl2 && vcpkg integrate install
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release
