name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Install libsdl2-dev
      run: sudo apt-get install libsdl2-dev
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: Compress output
      run: mkdir -p squeaker-linux && cp bin/squeaker squeaker-linux && tar -czvf squeaker-linux.tar.gz squeaker-linux
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: squeaker-linux.tar.gz
        path: squeaker-linux.tar.gz
